# https://woodruffw.github.io/zizmor/
rules:
  # See https://woodruffw.github.io/zizmor/audits/#template-injection
  template-injection:
    ignore:
      # The github.ref_name seems like it should be safe from injection
      # due to the rules for what Git will accept as a branch name
      - ci.yml:230:9
  unpinned-uses:
    config:
      policies:
        # We trust GitHub not to have a security incident
        actions/*: ref-pin
        github/codeql-action/*: ref-pin
        # And Codecov
        codecov/*: ref-pin
        # And astral
        astral-sh/setup-uv: ref-pin
        # Pypa is probably safe
        pypa/gh-action-pypi-publish: ref-pin
        # Both these are needed
        ncipollo/release-action: ref-pin
        release-flow/keep-a-changelog-action: ref-pin
        j178/prek-action: ref-pin
