name: ci
on:
  push:
  pull_request:
    branches:
      - main
      - develop
concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true
env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  DEFAULT_PYTHON_VERSION: "3.12"
  DEFAULT_UV_VERSION: "0.9.x"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install Hatch
        run: |
          uv tool install --python ${{ steps.setup-python.outputs.python-version }} --upgrade hatch
      - name: Lint project
        run: |
          hatch fmt --check
      - name: Check project typing
        run: |
          hatch run typing:run
      - name: Check files with prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
      - name: Validate the changelog
        uses: release-flow/keep-a-changelog-action@74931dec7ecdbfc8e38ac9ae7e8dd84c08db2f32 # v3
        with:
          command: query
          version: latest-or-unreleased
  tests:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    environment: unit-tests
    permissions:
      contents: read
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Pull Docker images
        run: |
          docker compose --file tests/docker/docker-compose.ci-test.yml pull --quiet
      - name: Show pulled image info
        run: |
          docker compose --file tests/docker/docker-compose.ci-test.yml config --images | \
            xargs docker inspect --format='{{join .RepoTags ", "}} ({{index .RepoDigests 0}}){{"\n"}}Labels: {{json .Config.Labels}}'
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv (PyPy)
        if: contains(matrix.python-version, 'pypy')
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ steps.setup-python.outputs.python-path }}
      - name: Install uv (CPython)
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch (PyPy)
        if: contains(matrix.python-version, 'pypy')
        run: |
          uv tool install --python ${{ steps.setup-python.outputs.python-path }} --upgrade hatch
      - name: Install Hatch (CPython)
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        run: |
          uv tool install --python ${{ matrix.python-version }} --upgrade hatch
      - name: Show environment
        run: |
          hatch test --show --python ${{ matrix.python-version }}
      - name: Run tests
        run: |
          hatch test --cover --junitxml=junit.xml -o junit_family=legacy --python ${{ matrix.python-version }}
      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.python-version }}
          report_type: coverage
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.python-version }}
          report_type: test_results
  test-edge:
    name: Test Gotenberg :edge
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - lint
    env:
      GOTENBERG_CLIENT_EDGE_TEST: 1
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Pull Docker images
        run: |
          docker compose --file tests/docker/docker-compose.ci-test-edge.yml pull --quiet
      - name: Show pulled image info
        run: |
          docker compose --file tests/docker/docker-compose.ci-test-edge.yml config --images | \
            xargs docker inspect --format='{{join .RepoTags ", "}} ({{index .RepoDigests 0}}){{"\n"}}Labels: {{json .Config.Labels}}'
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install Hatch
        run: |
          uv tool install --python ${{ steps.setup-python.outputs.python-version }} --upgrade hatch
      - name: Show environment
        run: |
          hatch test --show --python ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Run tests
        run: |
          hatch test --cover --python ${{ env.DEFAULT_PYTHON_VERSION }}
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install Hatch
        run: |
          uv tool install --python ${{ steps.setup-python.outputs.python-version }} --upgrade hatch
      - name: Build
        run: |
          hatch build --clean
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: dist/*
          if-no-files-found: error
          retention-days: 7
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: ${{ env.DEFAULT_UV_VERSION }}
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install Hatch
        run: |
          uv tool install --python ${{ steps.setup-python.outputs.python-version }} --upgrade hatch
      - name: Build Documentation
        run: |
          hatch run docs:build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: documentation
          path: site/*
          if-no-files-found: error
          retention-days: 7
      - name: Configure Git user
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Fetch gh-pages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git fetch origin gh-pages --depth=1
      - name: Deploy documentation
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          hatch run docs:deploy ${GITHUB_REF_NAME}
  create-release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - build
      - tests
      - documentation
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: dist
      - name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@74931dec7ecdbfc8e38ac9ae7e8dd84c08db2f32 # v3.0.0
        with:
          command: query
          version: ${{ github.ref_name }}
      - name: Display release info
        run: |
          echo "Version: ${STEPS_QUERY_RELEASE_INFO_OUTPUTS_VERSION}"
          echo "Date: ${STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_DATE}"
          echo "${STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_NOTES}"
        env:
          STEPS_QUERY_RELEASE_INFO_OUTPUTS_VERSION: ${{ steps.query-release-info.outputs.version }}
          STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_DATE: ${{ steps.query-release-info.outputs.release-date }}
          STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_NOTES: ${{ steps.query-release-info.outputs.release-notes }}
      - name: Create GitHub Release
        run: |
          printf "%s" "${STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_NOTES}" > notes.txt
          gh release create "${GITHUB_REF_NAME}" dist/*.tar.gz dist/*.whl --notes-file notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STEPS_QUERY_RELEASE_INFO_OUTPUTS_RELEASE_NOTES: ${{ steps.query-release-info.outputs.release-notes }}
  pypi-publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    needs:
      - build
      - tests
      - documentation
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifacts
          path: dist
      - name: Publish build to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
